# Generated by Django 5.2 on 2025-12-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_panchayat',
            fields=[
                ('PanchayatID', models.AutoField(primary_key=True, serialize=False)),
                ('PanchayatName', models.CharField(max_length=100)),
            ],
        ),
    ]
