# Generated by Django 5.2 on 2025-12-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_panchayat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ward',
            fields=[
                ('WardID', models.AutoField(primary_key=True, serialize=False)),
                ('WardName', models.CharField(max_length=100)),
                ('panchayatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_panchayat')),
            ],
        ),
    ]
