# Generated by Django 5.2 on 2025-12-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tbl_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_location',
        ),
    ]
