# Generated by Django 5.2 on 2025-12-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_taluk',
            fields=[
                ('TalukID', models.AutoField(primary_key=True, serialize=False)),
                ('TalukName', models.CharField(max_length=100)),
            ],
        ),
    ]
