# Generated by Django 5.2 on 2025-12-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_tbl_taluk'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_localbody_type',
            fields=[
                ('TypeID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
            ],
        ),
    ]
