# Generated by Django 5.2 on 2025-12-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_localbody_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_localbody',
            fields=[
                ('LocalbodyID', models.AutoField(primary_key=True, serialize=False)),
                ('LocalbodyName', models.CharField(max_length=100)),
                ('TalukId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_taluk')),
                ('TypeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_localbody_type')),
            ],
        ),
    ]
