# Generated by Django 5.2 on 2025-12-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_localbody'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_localbody',
            old_name='TypeName',
            new_name='TypeID',
        ),
    ]
