# Generated by Django 5.2 on 2025-12-12 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_rename_typename_tbl_localbody_typeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_ward',
            name='panchayatID',
        ),
        migrations.DeleteModel(
            name='tbl_panchayat',
        ),
        migrations.DeleteModel(
            name='tbl_ward',
        ),
    ]
