# Generated by Django 5.2 on 2025-12-12 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_tbl_ward_panchayatid_delete_tbl_panchayat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ward',
            fields=[
                ('WardID', models.AutoField(primary_key=True, serialize=False)),
                ('WardNumber', models.CharField(max_length=10)),
                ('LocalbodyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_localbody')),
            ],
        ),
    ]
