# Generated by Django 5.2 on 2026-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_disaster',
            fields=[
                ('DisasterID', models.AutoField(primary_key=True, serialize=False)),
                ('DisasterName', models.CharField(max_length=100)),
            ],
        ),
    ]
