# Generated by Django 5.2 on 2026-01-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_tbl_disaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_service_type',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=100)),
            ],
        ),
    ]
