# Generated by Django 5.2 on 2026-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='min_required_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
