# Generated by Django 5.2 on 2026-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tbl_subcategory_min_required_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='is_broadcasted',
            field=models.BooleanField(default=False),
        ),
    ]
