# Generated by Django 5.2 on 2025-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('LoginID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
