# Generated by Django 5.2 on 2025-12-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_ward'),
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ngo_reg',
            fields=[
                ('NGOID', models.AutoField(primary_key=True, serialize=False)),
                ('NGOname', models.CharField(max_length=200)),
                ('RegNumber', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('ContactNumber', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('ProofDocument', models.FileField(upload_to='ngo_proofs/')),
                ('hasVolunteers', models.CharField(max_length=10)),
                ('LocalbodyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_localbody')),
                ('LoginID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
                ('TalukID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_taluk')),
            ],
        ),
    ]
