# Generated by Django 5.2 on 2025-12-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_tbl_ngo_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_ngo_reg',
            old_name='ContactNumber',
            new_name='ContactNumber1',
        ),
        migrations.AddField(
            model_name='tbl_ngo_reg',
            name='ContactNumber2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
