# Generated by Django 5.2 on 2025-12-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_ward'),
        ('guestapp', '0003_rename_contactnumber_tbl_ngo_reg_contactnumber1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_volunteer_reg',
            fields=[
                ('VolunteerId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('DateofBirth', models.DateField()),
                ('age', models.IntegerField()),
                ('ContactNumber1', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=300)),
                ('availability_status', models.CharField(max_length=100)),
                ('LocalbodyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_localbody')),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_login')),
                ('TalukID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_taluk')),
            ],
        ),
    ]
