# Generated by Django 5.2 on 2026-01-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
        ('guestapp', '0004_tbl_volunteer_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_affected_individual',
            fields=[
                ('affectedID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('localbodyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_localbody')),
                ('talukID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_taluk')),
                ('wardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_ward')),
            ],
        ),
    ]
