# Generated by Django 5.2 on 2026-01-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0006_tbl_community_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_community_request',
            name='community_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
