# Generated by Django 5.2 on 2026-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0007_tbl_community_request_community_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_volunteer_reg',
            name='identity_proof',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_id_proofs/'),
        ),
        migrations.AddField(
            model_name='tbl_volunteer_reg',
            name='vol_image',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_images/'),
        ),
    ]
