# Generated by Django 5.2 on 2026-01-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
        ('guestapp', '0008_tbl_volunteer_reg_identity_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=100)),
                ('request_status', models.CharField(max_length=50)),
                ('affectedID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_affected_individual')),
                ('campID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_community_request')),
                ('disasterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_disaster')),
            ],
        ),
    ]
