# Generated by Django 5.2 on 2026-01-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
        ('guestapp', '0009_tbl_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request_service',
            fields=[
                ('request_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('categoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_request')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_service_type')),
                ('subCategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_subcategory')),
            ],
        ),
    ]
