# Generated by Django 5.2 on 2026-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0010_tbl_request_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request_service',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
