# Generated by Django 5.2 on 2026-01-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
        ('guestapp', '0011_alter_tbl_request_service_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_request',
            name='disasterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_disaster'),
        ),
        migrations.AlterField(
            model_name='tbl_request_service',
            name='requestID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_request'),
        ),
        migrations.AlterField(
            model_name='tbl_request_service',
            name='serviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_service_type'),
        ),
    ]
