# Generated by Django 5.2 on 2026-01-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0012_alter_tbl_request_disasterid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='NGOID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_ngo_reg'),
        ),
    ]
