# Generated by Django 5.2 on 2026-01-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0013_tbl_request_ngoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request_assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_quntity', models.IntegerField(blank=True, null=True)),
                ('assignment_status', models.CharField(max_length=50)),
                ('NGOID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_ngo_reg')),
                ('request_serviceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_request_service')),
            ],
        ),
    ]
