# Generated by Django 5.2 on 2026-01-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0014_tbl_request_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ngo_request_notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(default='Pending', max_length=20)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('NGOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_ngo_reg')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_request')),
            ],
        ),
    ]
