# Generated by Django 5.2 on 2026-01-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0015_tbl_ngo_request_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request_assignment',
            name='volunteerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_volunteer_reg'),
        ),
    ]
