# Generated by Django 5.2 on 2026-01-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0016_tbl_request_assignment_volunteerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_volunteer_reg',
            name='availability_status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
