# Generated by Django 5.2 on 2026-02-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0017_alter_tbl_volunteer_reg_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request_service',
            name='fulfilled_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
