# Generated by Django 5.2 on 2026-03-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0018_tbl_request_service_fulfilled_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ngo_volunteer_assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Emergency', 'Emergency')], default='Permanent', max_length=20)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('NGOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_ngo_reg')),
                ('VolunteerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_volunteer_reg', unique=True)),
            ],
            options={
                'unique_together': {('NGOID', 'VolunteerID')},
            },
        ),
    ]
