# Generated by Django 5.2 on 2026-01-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0013_tbl_service_type'),
        ('guestapp', '0004_tbl_volunteer_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ngo_helptype',
            fields=[
                ('ngoHelpID', models.AutoField(primary_key=True, serialize=False)),
                ('isActive', models.CharField(max_length=10)),
                ('NGOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbl_ngo_reg')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_service_type')),
                ('subCategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_subcategory')),
            ],
        ),
    ]
