# Generated by Django 5.2 on 2026-01-12 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGOapp', '0001_initial'),
        ('adminapp', '0013_tbl_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_ngo_helptype',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_ngo_helptype',
            name='categoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category'),
        ),
        migrations.AlterField(
            model_name='tbl_ngo_helptype',
            name='isActive',
            field=models.CharField(default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_ngo_helptype',
            name='serviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_service_type'),
        ),
        migrations.AlterField(
            model_name='tbl_ngo_helptype',
            name='subCategoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_subcategory'),
        ),
    ]
